# -*- coding: utf-8 -*-
"""Exercise1_YUTUC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7SZtNIjrVSYPabaqRC3d-zofOm6eVYP

#1 Display your name and your age
"""

name = "Thom Daniel C. Yutuc"
age = 18

print(f"I am {name} and I am {age} years old")

"""#2 Display 2 numbers and get the sum, product, quotient and difference"""

x = 10
y = 34

print(f'''The numbers are {x} and {y}.
Sum: {x + y}
Product: {x * y}
Quotient: {x / y}
Difference: {x - y}''')

"""#3 Display a string with no quotes and Display a string with single quotes and concatenate them"""

word_1 = "Hello"
word_2 = "'World'"

print(word_1 + word_2)

"""4 Assign two float values in 2 separate variables, get the sum and convert it to integer"""

x = 1.1
y = 3.1

print(int(x + y))