# -*- coding: utf-8 -*-
"""LabActivity1a_YUTUC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmiRF0Hs6wUZDY6kcfpJ2CHtmroI2WMW

This is part 1 of your LabActivity#1. Make sure to make a new copy of this notebook. (Filename: LabActivity1a_"SURNAME").

This is a recall of Python101

1 Input your fullname and section separately
"""

input("What is your full name: ")
input("What is your section: ")

"""#2 Allow the user to input a value(integer). Determine if the number is odd or even."""

number = int(input("Input an integer: "))

if number % 2 == 0:
  print(f"{number} is even")
else:
  print(f"{number} is odd")

"""3 Allow the user to input two integer values.  The first value should be the starting number.  The second value will be the last value.
Sample Output:
Enter first number: 1
Enter second number: 5
Series: 1 2 3 4 5
"""

x = int(input("Enter first number: "))
y = int(input("Enter second number (must be bigger than the first): "))

print("Series:", end = " ")
for i in range(x, y + 1):
  print(i, end = " ")

"""4 Allow the user to input three float values.  Determine the highest and lowest value among the three"""

float1 = float(input("Enter first float: "))
float2 = float(input("Enter second float: "))
float3 = float(input("Enter third float: "))

def highest (float1, float2, float3):
  if float1 > float2 and float1 > float3:
    print(f"{float1} is the highest")
  elif float2 > float1 and float2 > float3:
    print(f"{float2} is the highest")
  elif float3 > float1 and float3 > float2:
    print(f"{float3} is the highest")
  else:
    print("Error")

def lowest (float1, float2, float3):
  if float1 < float2 and float1 < float3:
    print(f"{float1} is the lowest")
  elif float2 < float1 and float2 < float3:
    print(f"{float2} is the lowest")
  elif float3 < float1 and float3 < float2:
    print(f"{float3} is the lowest")
  else:
    print("Error")

print()
highest (float1, float2, float3)
lowest (float1, float2, float3)